name: Format python code
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "hello"
          replace: "world"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: bug fixes
          title: bug fixes
          body: fix bugs
          labels: fix
          reviewers: starkgang
          branch: latestfix
